apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-commerce-cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-commerce-cart
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: e-commerce-cart
    spec:
      containers:
        - image: aflal/e-commerce-cart:97466560a8910992a1e17c6c9ff8996f7a5d309e
          name: e-commerce-cart-container
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"